# Generated by Django 2.1.1 on 2018-10-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='class_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
