# Generated by Django 2.1.2 on 2018-11-18 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('execplan', models.CharField(help_text='\n        0:5 0代表分钟，即每隔5分钟执行一次\n        1:5 1代表小时，即每隔5小时执行一次\n        2:5 2代表天，即每隔5天执行一次\n        ', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '成功'), (3, '失败')], default='0')),
                ('task_type', models.SmallIntegerField(choices=[(0, 'shell'), (1, 'perl'), (2, 'python')], default='0')),
                ('is_template', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('exec_type', models.SmallIntegerField(choices=[(0, '立即执行'), (1, '定时执行')], default='0')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('execplan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.ExecPlan')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.Asset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Task')),
            ],
            options={
                'db_table': 'task_host_relationship',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_log', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='hosts',
            field=models.ManyToManyField(through='tasks.TaskHost', to='cmdb.Asset'),
        ),
    ]
